"""
Django settings for mediator project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os


# OpenHIM mediator settings

OPENHIM_OPTIONS = {
    'username': 'user@example.com',
    'password': 'secret',
    'apiURL': 'https://server.example.com/',
    'verify_cert': True,

    'force_config': False,
    'interval': 10,

    'register': True,
    'heartbeat': True,
}

MEDIATOR_CONF = {
    'urn': f'urn:uuid:{os.environ["MEDIATOR_URN"]}',
    'version': '0.0.1',
    'name': 'Passthrough Mediator',
    'description': 'This is a passthrough mediator',
    'defaultChannelConfig': [
        {
            'name': 'Passthrough Mediator',
            'urlPattern': '/passthru/.*',
            'alerts': [],
            'txRerunAcl': [],
            'txViewFullAcl': [],
            'txViewAcl': [],
            'properties': [],
            'matchContentTypes': [],
            'routes': [
                {
                    'name': 'Passthrough Mediator Route',
                    'host': 'localhost',
                    'port': '4000',
                    'primary': True,
                    'type': 'http',
                }
            ],
            'allow': ['Sample Role'],
            'type': 'http',
        }
    ],
    'endpoints': [
        {
            'name': 'Passthrough Mediator Route',
            'host': 'localhost',
            'path': '/',
            'port': '4000',
            'primary': True,
            'type': 'http',
        }
    ],
    'configDefs': [
        {
            'param': 'upstreamUrl',
            'displayName': 'Upstream URL',
            'description': 'The URL of the service upstream of the mediator',
            'type': 'string',
            'template': [],
        }
    ],
    'config': {
        'upstreamUrl': 'http://sampleApplication:7001'
    }
}


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fqVfSvuOeLUQ10mvGViSSRF6L4FLsy7EvqROksWMOAG0B5Z9yy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'passthru',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mediator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mediator.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
